### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by edzer** [r-spatial/cesium#1]
Looks cool! When I try this, I see the folloing error in the browser:
```
An error occurred while rendering. Rendering has stopped.
SecurityError: Failed to construct 'Worker': Script at 'file:///tmp/RtmpGKS8wG/viewhtmla8f7c9cf8ba/lib/Cesium-1.61/Workers/cesiumWorkerBootstrapper.js' cannot be accessed from origin 'null'.
Error: Failed to construct 'Worker': Script at 'file:///tmp/RtmpGKS8wG/viewhtmla8f7c9cf8ba/lib/Cesium-1.61/Workers/cesiumWorkerBootstrapper.js' cannot be accessed from origin 'null'.
    at g (file:///tmp/RtmpGKS8wG/viewhtmla8f7c9cf8ba/lib/Cesium-1.61/Cesium.js:477:22385)
    at y.scheduleTask (file:///tmp/RtmpGKS8wG/viewhtmla8f7c9cf8ba/lib/Cesium-1.61/Cesium.js:477:23476)
    at g.createMesh (file:///tmp/RtmpGKS8wG/viewhtmla8f7c9cf8ba/lib/Cesium-1.61/Cesium.js:477:28947)
    at L (file:///tmp/RtmpGKS8wG/viewhtmla8f7c9cf8ba/lib/Cesium-1.61/Cesium.js:541:2730)
    at M (file:///tmp/RtmpGKS8wG/viewhtmla8f7c9cf8ba/lib/Cesium-1.61/Cesium.js:541:1281)
    at Function.P.processStateMachine (file:///tmp/RtmpGKS8wG/viewhtmla8f7c9cf8ba/lib/Cesium-1.61/Cesium.js:541:5565)
    at J.loadTile (file:///tmp/RtmpGKS8wG/viewhtmla8f7c9cf8ba/lib/Cesium-1.61/Cesium.js:542:26654)
    at z (file:///tmp/RtmpGKS8wG/viewhtmla8f7c9cf8ba/lib/Cesium-1.61/Cesium.js:543:23180)
    at B (file:///tmp/RtmpGKS8wG/viewhtmla8f7c9cf8ba/lib/Cesium-1.61/Cesium.js:543:22904)
    at b.endFrame (file:///tmp/RtmpGKS8wG/viewhtmla8f7c9cf8ba/lib/Cesium-1.61/Cesium.js:543:26513)
```

**Comment by tim-salabim** [comment]
What did you do?

**Comment by edzer** [comment]
Thank you. Copy and paste without thinking ;-)

**Comment by edzer** [comment]
```library(sf)
library(mapview)
library(cesium)
library(geojsonsf)

## standard data sets
fran = geojsonsf::sf_geojson(mapview::franconia)
cesium(data = fran)
```
leads to the following error in the browser:
```
An error occurred while rendering. Rendering has stopped.
SecurityError: Failed to construct 'Worker': Script at 'file:///tmp/RtmpvLTeNP/viewhtml48d61f4166fc/lib/Cesium-1.61/Workers/cesiumWorkerBootstrapper.js' cannot be accessed from origin 'null'.
Error: Failed to construct 'Worker': Script at 'file:///tmp/RtmpvLTeNP/viewhtml48d61f4166fc/lib/Cesium-1.61/Workers/cesiumWorkerBootstrapper.js' cannot be accessed from origin 'null'.
    at g (file:///tmp/RtmpvLTeNP/viewhtml48d61f4166fc/lib/Cesium-1.61/Cesium.js:477:22385)
    at y.scheduleTask (file:///tmp/RtmpvLTeNP/viewhtml48d61f4166fc/lib/Cesium-1.61/Cesium.js:477:23476)
    at g.createMesh (file:///tmp/RtmpvLTeNP/viewhtml48d61f4166fc/lib/Cesium-1.61/Cesium.js:477:28947)
    at L (file:///tmp/RtmpvLTeNP/viewhtml48d61f4166fc/lib/Cesium-1.61/Cesium.js:541:2730)
    at M (file:///tmp/RtmpvLTeNP/viewhtml48d61f4166fc/lib/Cesium-1.61/Cesium.js:541:1281)
    at Function.P.processStateMachine (file:///tmp/RtmpvLTeNP/viewhtml48d61f4166fc/lib/Cesium-1.61/Cesium.js:541:5565)
    at J.loadTile (file:///tmp/RtmpvLTeNP/viewhtml48d61f4166fc/lib/Cesium-1.61/Cesium.js:542:26654)
    at z (file:///tmp/RtmpvLTeNP/viewhtml48d61f4166fc/lib/Cesium-1.61/Cesium.js:543:23180)
    at B (file:///tmp/RtmpvLTeNP/viewhtml48d61f4166fc/lib/Cesium-1.61/Cesium.js:543:22904)
    at b.endFrame (file:///tmp/RtmpvLTeNP/viewhtml48d61f4166fc/lib/Cesium-1.61/Cesium.js:543:26513)
```
with
```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] geojsonsf_1.3.0 cesium_0.1      mapview_2.7.0   sf_0.8-0       

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2         compiler_3.6.1     later_0.8.0        base64enc_0.1-3   
 [5] class_7.3-15       tools_3.6.1        digest_0.6.20      jsonlite_1.6      
 [9] satellite_1.0.1    lattice_0.20-38    viridisLite_0.3.0  png_0.1-7         
[13] shiny_1.3.2        DBI_1.0.0          crosstalk_1.0.0    yaml_2.2.0        
[17] e1071_1.7-2        raster_3.0-2       htmlwidgets_1.3    classInt_0.4-2    
[21] stats4_3.6.1       leaflet_2.0.2      grid_3.6.1         webshot_0.5.1     
[25] R6_2.4.0           sp_1.3-2           magrittr_1.5       scales_1.0.0      
[29] promises_1.0.1     codetools_0.2-16   htmltools_0.3.6    units_0.6-4       
[33] mime_0.7           xtable_1.8-4       colorspace_1.4-1   httpuv_1.5.1      
[37] KernSmooth_2.23-15 munsell_0.5.0     
```

**Comment by fdetsch** [comment]
When I run @edzer's code, I get the following error in RStudio viewer:

![error_cesium](https://user-images.githubusercontent.com/3940660/64515045-249e9c00-d2ec-11e9-8ecc-5e8feca55f55.png)

Furthermore, there's only a black screen when opening the .html in Chrome. In Edge, it works like a charm. 

Here's my `sessionInfo()`:

```r
[master]> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] geojsonsf_1.3.0 cesium_0.1      mapview_2.7.0  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2         compiler_3.6.1     later_0.8.0        base64enc_0.1-3    class_7.3-15      
 [6] tools_3.6.1        digest_0.6.20      jsonlite_1.6       viridisLite_0.3.0  satellite_1.0.1   
[11] lattice_0.20-38    png_0.1-7          shiny_1.3.2        DBI_1.0.0          rstudioapi_0.10   
[16] crosstalk_1.0.0    yaml_2.2.0         e1071_1.7-2        raster_3.0-2       htmlwidgets_1.3   
[21] webshot_0.5.1      stats4_3.6.1       classInt_0.4-1     leaflet_2.0.2      grid_3.6.1        
[26] prompt_1.0.0       sf_0.7-7           R6_2.4.0           sp_1.3-1           magrittr_1.5      
[31] scales_1.0.0       codetools_0.2-16   clisymbols_1.2.0   promises_1.0.1     htmltools_0.3.6   
[36] units_0.6-4        mime_0.7           xtable_1.8-4       colorspace_1.4-1   httpuv_1.5.1      
[41] KernSmooth_2.23-15 munsell_0.5.0      crayon_1.3.4      
```

**Comment by tim-salabim** [comment]
In chrome on windows I get:

![image](https://user-images.githubusercontent.com/2826432/64516160-46991e00-d2ee-11e9-95af-5d4063b81a34.png)

In RStudio viewer it renders but is flickering constantly...

**Comment by edzer** [comment]
For me, it works fine in rstudio.

**Comment by tim-salabim** [comment]
On linux it works fine for me in both RStudio and Firefox
